services:

  dts-os-backend:
    build:
      context: . # Include the entire project directory
      dockerfile: ./backend/Dockerfile # Specify the backend Dockerfile
    container_name: dts-os-backend
    ports:
      - 127.0.0.1:8989:8080
    environment:
      POSTGRES_HOST: ${DB_HOST:-dts-os-db}
      POSTGRES_PORT: ${DB_PORT:-5432}
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_SCHEMA: ${DB_SCHEMA:-public}
      POSTGRES_URL: jdbc:postgresql://${DB_HOST:-dts-os-db}:${DB_PORT:-5432}/${DB_NAME:-postgres}?currentSchema=${DB_SCHEMA:-public}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - dts-os-db

  dts-os-db:
    image: postgres:17.0
    restart: unless-stopped
    container_name: dts-os-db
    ports:
      - 127.0.0.1:5431:5432
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
